version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      SPRING_DATA_MONGODB_URI: mongodb://root:example@localhost:27017/mouts?authSource=admin
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: spring_app
    restart: always
    depends_on:
      - mongo
      - redis
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:example@mongo:27017/mouts?authSource=admin
      SPRING_REDIS_HOST: redis
    networks:
      - app_network

volumes:
  mongo_data:

networks:
  app_network:
